### ISSUE TITLE
[Issue] Editor(next) is not shown in Android

### ISSUE THREAD

**Issue by JaeWangL** [imnapo/react-native-cn-richtext-editor#110]
Stable version is ok. But, in next version, and in Android, I can see just white page
My OS is Windows. so, I don't now whether work in iOS or not

```
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-cn-richtext-editor": "^2.0.0-rc3",
```
```
    import CNEditor, { getDefaultStyles, CNToolbar } from 'react-native-cn-richtext-editor';

    const [selectedTag, setSelectedTag] = useState('body');
    const [selectedStyles, setSelectedStyles] = useState<string[]>([]);
    const editorRef = useRef(null);
```
```
                <CNEditor
                    ref={editorRef}
                    onSelectedTagChanged={setSelectedTag}
                    onSelectedStyleChanged={setSelectedStyles}
                    style={{ backgroundColor: '#000000' }}
                    styleList={getDefaultStyles()}
                />
```

**Comment by beisert1** [comment]
@JaeWangL This is an issue with the KeyboardAvoidingView component, I was able to fix by adding conditional props if Android.

`<KeyboardAvoidingView behavior={IS_IOS ? "padding" : "height"} enabled keyboardVerticalOffset={IS_IOS ? 0 : 30} style={styles.root}>`

**Comment by JaeWangL** [comment]
> @JaeWangL This is an issue with the KeyboardAvoidingView component, I was able to fix by adding conditional props if Android.
> 
> `<KeyboardAvoidingView behavior={IS_IOS ? "padding" : "height"} enabled keyboardVerticalOffset={IS_IOS ? 0 : 30} style={styles.root}>`

Thank you!!
