### ISSUE TITLE
Text colors are treated as independent Styles - resulting in SPAN tag with multiple colors

### ISSUE THREAD

**Issue by bumpingChris** [imnapo/react-native-cn-richtext-editor#153]
When selecting different text colors one after another (even without typing anything), CNTextInput treats each selection as a different Style. This leads to incorrect color behavior when changing from one color to another. Specifically, when changing back to a previously used color.

**Comment by imnapo** [comment]
This library is deprecated Use [react-native-cn-quill](https://github.com/imnapo/react-native-cn-quill#readme) instead.
