### ISSUE TITLE
Serious bug when input Chinese or other word in such case(see the pic)

### ISSUE THREAD

**Issue by flyinghawker** [imnapo/react-native-cn-richtext-editor#16]
**When input Chinese**
<img width="350" alt="screen shot 2019-02-19 at 3 00 12 am" src="https://user-images.githubusercontent.com/13193798/52971457-8223d780-33f2-11e9-909b-af9d016717a1.png">

**When input English**
<img width="324" alt="screen shot 2019-02-19 at 3 03 25 am" src="https://user-images.githubusercontent.com/13193798/52971585-f6f71180-33f2-11e9-9d2a-a4a9ff8dcc0d.png">

When you type the word and see the light blue background behind unfinished, and then you will get bug when you press next button from soft keyboard: changing new line and the word just typed will be changed a little bit like from '**Googleed**' to '**Googled**'

**Comment by imnapo** [comment]
@flyinghawker That's probably a bug related to text replacement. I will investigate this today.
