### ISSUE TITLE
New line gets rid of selected tag

### ISSUE THREAD

**Issue by RukaiJohn** [imnapo/react-native-cn-richtext-editor#21]
When I click on the new line of the android keyboard, it gets rid of bold, italic, etc. that I selected.

**Comment by ohpax** [comment]
Seems like something we should improve for the user convenience. I will leave this ticket open until we fix it.

**Comment by ohpax** [comment]
@imnapo do you have any update on this?

**Comment by imnapo** [comment]
Hey, I just released a new version 1.0.34 of the library. 
Please try the new version and see if it addresses your issue. If not, please open a new issue.
