### ISSUE TITLE
Bug: CNRichTextView failed to render normal text

### ISSUE THREAD

**Issue by flyinghawker** [imnapo/react-native-cn-richtext-editor#23]
I play around the basic logic that convert editor value to html by `convertToHtmlString` (assuming to save it in db), and directly convert the result back to object by `convertToObject`, render the result through CNRichTextView. There is error that stop it from rendering anything.
Here are some snapshots and piece of demo code.
      `    {this.state.back && <CNRichTextView text={this.state.back} />}`

```
  demo = () => {
    const res = convertToHtmlString(this.state.value);
    console.log(res);
    const back = convertToObject(res);
    console.log(back);
    this.setState({ back });
  };
```

<img width="713" alt="screen shot 2019-03-08 at 11 25 27 am" src="https://user-images.githubusercontent.com/13193798/54005584-f69d9b00-4194-11e9-902a-a829517e6de6.png">
<img width="717" alt="screen shot 2019-03-08 at 11 25 38 am" src="https://user-images.githubusercontent.com/13193798/54005586-f7363180-4194-11e9-8209-4eea487a6463.png">
<img width="314" alt="screen shot 2019-03-08 at 11 25 51 am" src="https://user-images.githubusercontent.com/13193798/54005587-f7cec800-4194-11e9-9b32-41f3138d006d.png">

**Comment by LudoFont** [comment]
hi,

same here, could you please take a look at it and document the CNRichTextView ?

**Comment by LudoFont** [comment]
Got it, CNRichTextView want an html string for the "text" property, so if you don't convert back your html string, it should work.
To init a CNRichTextView without value (for my example, where it's load async), just set "<div></div>" as the text property of the CNRichTextView.

**Comment by imnapo** [comment]
@flyinghawker sorry for the late response. as @LudoFont mentioned , **CNRichTextView** **Text** field needs a html string, so you shouldn't covert it back to object.

Something like this: 
`const text = '<div></div> // or any other html converted using convertToHtmlString()`
`<CNRichTextView text={text} />`

**Comment by LudoFont** [comment]
@imnapo thank you for that great plugin by the way ! ;)

**Comment by flyinghawker** [comment]
@imnapo @LudoFont Got it, thank you guys.

**Comment by bunyy** [comment]
@imnapo  Thank you man for great plugin
