### ISSUE TITLE
Initial Value for Editor

### ISSUE THREAD

**Issue by Messi10AP** [imnapo/react-native-cn-richtext-editor#28]
If I edit the state.value, (changing it from getInitialObject()), the editor will no longer work

**Comment by ohpax** [comment]
Please post your code here to be able to help you.

**Comment by Messi10AP** [comment]
constructor(props) {
        super(props);
        

        this.state = {
            selectedTag : 'body',
            selectedColor : 'default',
            selectedHighlight: 'default',
            colors : ['red', 'green', 'blue'],
            highlights:['yellow_hl','pink_hl', 'orange_hl', 'green_hl','purple_hl','blue_hl'],
            selectedStyles : [],
            value: [getInitialObject],
            keyboardPressed: false
        };

        this.state.value = [getInitialObject()];
        this.onValueChanged(convertToObject("<div><p><span>Test Initial Test</span></p></div>"));
        this.editor = null;

    }

In my constructor, I wanted to set up the editor with text already inside

**Comment by ohpax** [comment]
You just need to replace this =>
```
    this.state.value = [getInitialObject()];
    this.onValueChanged(convertToObject("<div><p><span>Test Initial Test</span></p></div>"));
```

with this => 
```
this.state.value = convertToObject("<div><p><span>Test Initial Test</span></p></div>");
```

**Comment by Messi10AP** [comment]
Thank you!!
