### ISSUE TITLE
Which license for this repo ?

### ISSUE THREAD

**Issue by jsamr** [imnapo/react-native-cn-richtext-editor#30]
I could offer a PR for a MIT license for example.

**Comment by ohpax** [comment]
At this point, we have it as ISC. Do you see any value to change it to MIT ?

**Comment by jsamr** [comment]
@ohpax Yeah I closed after noticing the license mention in the README ; would be nice to have the full license within the repo IMHO.

**Comment by morenoh149** [comment]
license MIT in the repo is most obvious and not surprising.

**Comment by morenoh149** [comment]
https://help.github.com/en/articles/licensing-a-repository#determining-the-location-of-your-license advises License file in root of repo. This may help with automated tools that expect this.
