### ISSUE TITLE
Change Color of Icons

### ISSUE THREAD

**Issue by Messi10AP** [imnapo/react-native-cn-richtext-editor#33]
<CNToolbar
                        size={28}
                        
                        bold={<MaterialCommunityIcons 
                            name="format-bold"
                            size={12}
                            color="#0120c1" />}
                        italic={<MaterialCommunityIcons 
                            name="format-italic"
                            color="#ffffff"  />}
                        underline={
                            <MaterialCommunityIcons 
                            name="format-underline"
                            color="#ffffff"  />
                        }
                        lineThrough={
                            <MaterialCommunityIcons 
                            name="format-strikethrough-variant"
                            color="#ffffff"  />
                        }
                        body={<MaterialCommunityIcons name="format-text" />}
                        title={
                            <MaterialCommunityIcons name="format-header-1" />
                        }
                        heading={
                            <MaterialCommunityIcons name="format-header-3" />
                        }
                        ul={
                            <MaterialCommunityIcons name="format-list-bulleted" />
                        }
                        ol={
                            <MaterialCommunityIcons name="format-list-numbers" />
                        }
                        indent={
                            <MaterialCommunityIcons name="format-list-numbers" />
                        }
                        foreColor={this.renderColorSelector()}
                        highlight={this.renderHighlight()}
                        selectedTag={this.state.selectedTag}
                        selectedStyles={this.state.selectedStyles}
                        onStyleKeyPress={this.onStyleKeyPress}
                    />

This code should change the color of the first 4 icons (and the size of the first) but they stay the same size and color, regardless of what i make the values

**Comment by Messi10AP** [comment]
i fixed this by added the color tag for CNToolbar instead of for each icon

**Comment by imnapo** [comment]
@Messi10AP you may also use **toolbar**'s new props added in V1.0.33 
such as:  _style, color, backgroundColor, selectedColor, selectedBackgroundColor, iconContainerStyle_

You may also check [documentation ](https://github.com/imnapo/react-native-cn-richtext-editor#cntoolbar) and [demo app](https://github.com/imnapo/react-native-cn-richtext-editor/blob/master/expo-demo/App.js).
