### ISSUE TITLE
CNRichTextView showing nothing

### ISSUE THREAD

**Issue by koo27** [imnapo/react-native-cn-richtext-editor#34]
I'm trying to use `<CNRichTextView text={text} />` but it doesn't seem to work.
I set text as simple html (`<div><h1><span style="font-weight: bold;">Heading 1</span></h1></div>` for example - that is produced by `convertToHtmlString()` ) but it just shows nothing at all.

If I `convertToObject()` and set it into `CNRichTextEditor` it works properly and shows up good.

I'm using a simple rendering without anything else in the screen.

Any idea what I'm doing wrong?

P.S.
It would be very useful to have a doc about CNRichTextView, since I discovered it exploring the src directory.

**Comment by imnapo** [comment]
@koo27 , I tried below sample and it worked fine. Please 

- Be sure to pass htmlstring to **CNRichTextView** 
- and pass a positioning style to  **CNRichTextView** like `style={{flex: 1}}`

**Simple Usage :**
```
import React, { Component } from 'react';
import { View } from 'react-native';
import { CNRichTextView } from "react-native-cn-richtext-editor";

class App extends Component {
constructor(props) {
   super(props);
        
    this.state = {
        text: '<div><h1><span style="font-weight: bold;">Heading 1</span></h1></div>'
    };
 }

render() {
   return (
         <View style={{
             flex: 1, padding: 20
         }}>
             <CNRichTextView
              style={{flex: 1}}
              text={this.state.text}
             />
         </View>
     );
 }
}
```
And we'll add this component to our documentation for sure :)

**Comment by koo27** [comment]
@imnapo Thank you very much, it works perfectly. I was missing the flex:1 style, my bad.
