### ISSUE TITLE
change foreColor does not work at first time

### ISSUE THREAD

**Issue by pingxiaodou** [imnapo/react-native-cn-richtext-editor#35]
![1553671565484](https://user-images.githubusercontent.com/23648004/55057828-48a35380-50a5-11e9-80fa-838bc0fe15ff.gif)

As you can see,The text color does not change for the first time, and the second time changes.

**Comment by imnapo** [comment]
Hey, I just released a new version 1.0.34 of the library. 
Please try the new version and see if it addresses your issue. If not, please open a new issue.
