### ISSUE TITLE
Scroll position not updating well when using line break on iOS

### ISSUE THREAD

**Issue by rmarquois** [imnapo/react-native-cn-richtext-editor#36]
When using line break on iOS I have the following behavior :

![keyboard-ios-nok](https://user-images.githubusercontent.com/1659282/55069971-809a9e80-5085-11e9-8923-db72ed674b96.gif)

Scroll position is not updating except if I type something from keyboard.

I removed ScrollView component in the `CNRichTextEditor.js` file and I also removed the `scrollEnabled` TextInput prop in `CNTextInput.js` file and I have the following behavior :

![keyboard-ios-ok](https://user-images.githubusercontent.com/1659282/55070177-fb63b980-5085-11e9-9f1e-f55f7f1263be.gif)

Do you think the ScrollView component can be removed to keep the default scroll behavior of TextInput ?

Note : on Android everything works fine for both cases

**Comment by ergunyasar** [comment]
@rmarquois I just tried your proposal. It indeed makes a better UI experience, however it doesn't work when you implement image upload. Apparently, editor creates array of rn elements and when you upload image next text input is below the image. Since scrollview is gone you cannot scroll anymore.

**Comment by ohpax** [comment]
Interesting, I 'll investigate this further

**Comment by imnapo** [comment]
Hey, I just released a new version 1.0.34 of the library. 
Please try the new version and see if it addresses your issue. If not, please open a new issue.
