### ISSUE TITLE
Place for title?

### ISSUE THREAD

**Issue by Messi10AP** [imnapo/react-native-cn-richtext-editor#37]
Is there a component which can serve as a place to put a title?

**Comment by ohpax** [comment]
H1 and H3 are for title size texts, or I  miss misunderstood your question?

**Comment by Messi10AP** [comment]
Yes, I get that, however I need and editor that also allows for a title field to be shown (seperate from the editor)

**Comment by ohpax** [comment]
You can just add another input separate from the editor. I don't think that is something which this component should provide.
