### ISSUE TITLE
copy paste does not update value in text

### ISSUE THREAD

**Issue by MuzavaziTawa** [imnapo/react-native-cn-richtext-editor#55]
Hello there.

When i copy text to clipboard and paste it in the text editor, the editor records the length of text as 0 and text as nothing. I initially wanted to validate if the text editor is empty and so if you can help me with this on how i can validate it as empty or if i can override the copy paste method to add text to the value

**Comment by imnapo** [comment]
Hi @MuzavaziTawa , I checked copy text to clipboard and paste it in the editor and it works properly in both platforms. Please check your RN version to be at least "0.57.5".
To be able to check if editor is empty or not, you may check editor's value prop which is a JavaScript array object as below:
`value.length === 1 && value[0].content.length === 1 && value[0].content[0].text.length === 0`

**Comment by MuzavaziTawa** [comment]
Thanks this seems to be working fine.
