### ISSUE TITLE
How to manage videos?

### ISSUE THREAD

**Issue by dedevelopersltd** [imnapo/react-native-cn-richtext-editor#58]
Hi,
I want to upload videos from this text editor in react native expo, every other thing is working fine, but I am unable to work on how to add/embed videos.
Can anyone help me who has modified this library?

**Comment by imnapo** [comment]
Hello, uploading video isn't supported yet.

**Comment by aydarda** [comment]
Can I upload images?

**Comment by YoungDu** [comment]
> Can I upload images?

You can by using toolbar
