### ISSUE TITLE
Default Font Size of Editor

### ISSUE THREAD

**Issue by yudzuru** [imnapo/react-native-cn-richtext-editor#62]
I've set the body style inside styleList to { fontSize:12 }.
But when I open the view which contains the editor, 
the default fontSize of the input field is much larger than 12.

I checked into the source code, it seems that the initial fontSize of the editor is hardcoded to 20.

Will there be any enhancement on this?

**Comment by imnapo** [comment]
@yudzuru I fixed it and publish v.38. You may use custom Style-list as below:
 
```
render() {
 let customStyles = {...defaultStyles, body: {fontSize: 12}, heading : {fontSize: 16}, title : {fontSize: 20}};
 return (
  ....
  <CNRichTextEditor                   
  ...
   styleList={customStyles}
  />  
 ...   
 );
}
```

**Comment by yudzuru** [comment]
@imnapo Great! Thanks for your quick update.
