### ISSUE TITLE
Custom style not working for Unordered list

### ISSUE THREAD

**Issue by DaniAkash** [imnapo/react-native-cn-richtext-editor#65]
I'm using the latest version of the package. The unordered list doesn't have the custom style I applied when I create a new line. however, it works if I add a backspace after creating this line. You can find the interaction below:

![interaction-demo](https://s3.gifyu.com/images/ezgif-3-9143af977f7d.gif)

**Comment by imnapo** [comment]
@DaniAkash, Sorry for late answare.
You may fix it by adding custom styles for `ul` and `ol` for now, as below:
```
  let customStyles = {...defaultStyles, body: {fontSize: 12}, heading : {fontSize: 16}
        , title : {fontSize: 20}, ol : {fontSize: 12 }, ul: {fontSize: 12}
    };
```

**Comment by DaniAkash** [comment]
Tried it, but it's not working. I forked this repo, applied my own styles to the styles inside your codebase and it's still not helping... 
Refer - https://github.com/DaniAkash/react-native-cn-richtext-editor/tree/custom-theme

Also, another serious issue is, if I give a prefilled value for the text editor using `convertToObject(initialHtml)` none of the styles are getting applied...

**Comment by imnapo** [comment]
I've checked again and it works as exptected here. Plz specify more details. You may also check our demo app. 
be noticed to pass custom styles to `convertToObject`. 
`convertToObject(initialHtml, customStyles)`.
