### ISSUE TITLE
CNRichTextView no Number of Lines

### ISSUE THREAD

**Issue by kehobert** [imnapo/react-native-cn-richtext-editor#71]
Hello, thank you for this awsome library first of all,

I saw 3 properties of CNRichTextView (Text, style, styleList). I want to make preview in a list like this
![Screenshot_2019-08-14-09-58-30-581_host exp exponent](https://user-images.githubusercontent.com/34390688/62991635-81886d00-be7a-11e9-969c-07d3a6ff09b5.png)

But unfortunately I can't limit the **number of lines** to make it good. Is it possible to limit the amount of text / container height to make the preview not too big?

Thanks

**Comment by imnapo** [comment]
Hi @kehobert, you may use a `ScrollView `as a container of CNRichTextView and use flex display:
ex.
```
<View style={{ flexGrow: 1}}>
        <ScrollView scrollEnabled={false} 
        showsVerticalScrollIndicator={false} 
        contentContainerStyle={{flex: 1}}
        >
          <CNRichTextView text={content} style={{flex: 1}} />
        </ScrollView>
</View>
```
