### ISSUE TITLE
Issue: How can I center the icons?

### ISSUE THREAD

**Issue by pidmindiz** [imnapo/react-native-cn-richtext-editor#74]
![image](https://user-images.githubusercontent.com/3277999/63070950-ce079300-bee2-11e9-93fe-9f27d41ce7b9.png)

`<CNToolbar
....  
style={{
                alignItems: "center",
                flexDirection: "row"
              }}
              iconContainerStyle={{
                alignItems: "center",
                flexDirection: "row"
              }}`

**Comment by imnapo** [comment]
Please check the documentation.
