### ISSUE TITLE
When start typing, cursor start moving arround characters

### ISSUE THREAD

**Issue by Waqas-Jani** [imnapo/react-native-cn-richtext-editor#79]
it's a very good lib.
when i'm typing then cursor start moving arround characters fastly one point to another point. therefore text type not correctly.
example: if typing.. "have" 
then cursor start moive arround 'v' and 'e', or 'a' and 'e'. as well as 'space' to 'a'. etc., 
therefor text not writed correclty . haev... this is  typing issue  for any kind of text. cursor not still on it's position after start typing.
plz fix that.. thanks

**Comment by ajithv11** [comment]
Did you find any solution for this?

**Comment by Waqas-Jani** [comment]
no @ajithv11  .. have you faced this issue??

**Comment by ajithv11** [comment]
Yes, I am trying to fix this. It works in the demo application with expo

But not working for my project my react-native version is 0.60.4.   
@Waqas-Jani   Are you working on this for fixing the same?

**Comment by Waqas-Jani** [comment]
i try it. old version and work fine.. but not latest ..

**Comment by Waqas-Jani** [comment]
i'm not using wth expo..

**Comment by ajithv11** [comment]
> i try it. old version and work fine.. but not latest ..

Which react version have you tred?

**Comment by Waqas-Jani** [comment]
react-native 0.60.5. 
this lib version 1.0.40.

**Comment by ajithv11** [comment]
> react-native 0.60.5.
> this lib version 1.0.40.

This is your working version ?

**Comment by Waqas-Jani** [comment]
no.. 
this version .working. 
react-native-cn-richtext-editor: "1.0.35",

**Comment by ajithv11** [comment]
> no..
> this version .working.
> react-native-cn-richtext-editor: "1.0.35",

And your react-native version

For me its not working with react-native-cn-richtext-editor: "1.0.35", and react-native 0.60.5

**Comment by ajithv11** [comment]
@Waqas-Jani  Could you please tell the working version of your react-native-cn-richtext-editor  & react-native ?

**Comment by Waqas-Jani** [comment]
> @Waqas-Jani Could you please tell the working version of your react-native-cn-richtext-editor & react-native ?
working... 
"react-native": "^0.59.8",
 "react-native-cn-richtext-editor": "^1.0.35",

**Comment by imnapo** [comment]
Hi guys, as in : #70, this issue is related to react-native library version > 0.59.8 and you may follow related issue there.

**Comment by Waqas-Jani** [comment]
@imnapo  this issue occure in latest version of this lib

**Comment by Waqas-Jani** [comment]
react-native latest version TextInput working ok.

**Comment by imnapo** [comment]
You may specify `selection` prop also.
I've checked below code with RN v-0.60.5 on android device and its not working there.
```
import React from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {text: '', selection: {start: 0, end: 0}};
  }

  render() {

    return (
      <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <TextInput
          style={{height: 80, borderWidth: 1}}
          selection={this.state.selection}
          onSelectionChange={(event) => this.setState({selection: event.nativeEvent.selection})}
          placeholder="Type here to translate!"
          onChangeText={(text) => this.setState({text})}
          value={this.state.text}
          />
    </View>
  );
}
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: '#fff',
    alignItems: 'stretch',
    justifyContent: 'center',
  },
});
```

**Comment by Waqas-Jani** [comment]
i also check TextInput "react-native": "0.60.5", and it's work fine

**Comment by sushantb21** [comment]
use this code
<CNRichTextEditor
ref={input => this.editor = input}
onSelectedTagChanged={() => this.onSelectedTagChanged}
onSelectedStyleChanged={() => this.onSelectedStyleChanged}
value={this.state.value}
style={{ backgroundColor : '#fff'}}
styleList={defaultStyles}
onValueChanged={() => this.onValueChanged}
/>
